### ISSUE TITLE
Can you please downgrade to .NET 4.5.x if possible?

### ISSUE THREAD

**Issue by StefH** [mikeobrien/WebApi.StructureMap#1]
I'm unable to use this project in a .NET 4.5.2 project. Can you please make this library + NuGet compatible with the lowest .NET possible?

**Comment by mikeobrien** [comment]
I'm pretty slammed right now but when I get a chance I'll add a 4.5.x assembly to the nuget. I'd give [this nuget](https://www.nuget.org/packages/StructureMap.WebApi2/) a try in the meantime.

**Comment by StefH** [comment]
That NuGet (**StructureMap.WebApi2**) depends on StructureMap version 3.x, and I would like to use version 4.

**Comment by mikeobrien** [comment]
Ah, gotcha, I'll see what I can do.

**Comment by StefH** [comment]
I will make a PR.

**Comment by mikeobrien** [comment]
Just pushed a nuget that targets both `4.5.2` and `4.6.2` so you should be good to go. Let me know if you have any issues.

**Comment by StefH** [comment]
Just look at nuget, the latest is 1.0.18 ? Is that intentional? Because I would expect version 1.0.8

Btw creating a nuget package is very easy with the new csproj format in vs2017. No need for external tools or a spec file.

I can help you with converting this project.

**Comment by mikeobrien** [comment]
Yeah, I made some changes to the build script so it caused the version to
increment a few times.

Thx for the offer but the nuget is built and deployed automatically by a
build server.

**Comment by StefH** [comment]
I see that indeed the build is green again.

Thanks for your help, i will try next week.
