### ISSUE TITLE
Access to container.WhatDoIHave();

### ISSUE THREAD

**Issue by TonyBurnettSchoola** [mikeobrien/WebApi.StructureMap#3]
After I call...

`GlobalConfiguration.Configuration.UseStructureMap<MyRegistry>();`

...how can I access the container so I can call WhatDoIHave()?

**Comment by mikeobrien** [comment]
You can create the container and pass it in, then you'd have full access to
it. There is an overload that takes a container.

**Comment by TonyBurnettSchoola** [comment]
Got it, thanks.

**Comment by mikeobrien** [comment]
👍
