### ISSUE TITLE
Exception when HttpActionExecutedContext.Response is empty

### ISSUE THREAD

**Issue by ptixed** [mikeobrien/WebApi.StructureMap#4]
Extension methods can throw an exception from [here](https://github.com/mikeobrien/WebApi.StructureMap/blob/62a100826345c1cf9017253442f29499c3d7f76f/src/WebApi.StructureMap/Extensions.cs#L82) whenever some arguments are null. This happens e.g. when HttpActionExecutedContext does not yet have a Response.

**Comment by mikeobrien** [comment]
I'm not maintaining this lib and don't use WebApi anymore, but if you wanted to tackle this, a PR would be awesome.

**Comment by mikeobrien** [comment]
Thx! Pushed to nuget, will take a bit to validate and index.

**Comment by ptixed** [comment]
Yay! My first accepted PR, thanks!

**Comment by mikeobrien** [comment]
Awesome! :D
