### ISSUE TITLE
NuGet warning "WebApi.StructureMap 1.0.22 depends on structuremap (>= 4.1.0) but structuremap 4.1.0 was not found."

### ISSUE THREAD

**Issue by misha-fm** [mikeobrien/WebApi.StructureMap#6]
Steps to reproduce:
1. Install WebApi.StructureMap 1.0.22 as NuGet into a project
2. Build the project.

Then the warning "_NU1603: WebApi.StructureMap 1.0.22 depends on structuremap (>= 4.1.0) but structuremap 4.1.0 was not found. An approximate best match of structuremap 4.1.0.361 was resolved._" is shown.

As described here https://github.com/NuGet/Home/issues/5764#issuecomment-323613059, it happens because WebApi.StructureMap 1.0.22 depends on minimum version 4.1.0 of StructureMap nuget, which does not exist in StructureMap package source (https://www.nuget.org/packages/StructureMap):

![image](https://user-images.githubusercontent.com/9195593/47347265-2c8f2680-d6af-11e8-9650-5433bc00c1cb.png)

**Comment by mikeobrien** [comment]
Thx for the PR! Sorry for the delay merging it, on holiday. Just pushed, will show up shortly in the gallery after the package has been verified/indexed, `v1.0.23`.
